/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsuranceTypeRouteImport } from './routes/insurance.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceTypeRoute = InsuranceTypeRouteImport.update({
  id: '/insurance/$type',
  path: '/insurance/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insurance/$type': typeof InsuranceTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insurance/$type': typeof InsuranceTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insurance/$type': typeof InsuranceTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/insurance/$type'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/insurance/$type'
  id: '__root__' | '/' | '/insurance/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsuranceTypeRoute: typeof InsuranceTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/$type': {
      id: '/insurance/$type'
      path: '/insurance/$type'
      fullPath: '/insurance/$type'
      preLoaderRoute: typeof InsuranceTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsuranceTypeRoute: InsuranceTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
